version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass foobared
    volumes:
      - ./redis-data:/data
  python:
    restart: always
    tty: true
    build: .
    depends_on:
      - redis